import json
import boto3
import urllib.request
import urllib.parse
from datetime import datetime, timedelta
from boto3.dynamodb.conditions import Key
from decimal import Decimal

dynamodb = boto3.resource('dynamodb', region_name='ap-south-1')
ssm = boto3.client('ssm', region_name='ap-south-1')

def get_secret(name):
    return ssm.get_parameter(
        Name=name,
        WithDecryption=True
    )['Parameter']['Value']

def http_post_json(url, data, headers={}):
    body = json.dumps(data).encode('utf-8')
    headers['Content-Type'] = 'application/json'
    req = urllib.request.Request(
        url, data=body, headers=headers, method='POST'
    )
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read().decode('utf-8'))

def http_get(url, headers):
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read().decode('utf-8'))

def get_time_context():
    hour = datetime.now().hour
    day = datetime.now().strftime('%A')
    if hour < 7:
        return "late night", "deeply introspective, minimal, calm"
    elif hour < 9:
        return "early morning", "gentle, slowly energizing, hopeful"
    elif hour < 12:
        return "morning", "upbeat, motivated, positive"
    elif hour < 14:
        return "lunch", "relaxed, feel good, midday"
    elif hour < 17:
        return "afternoon", "focused, steady, productive"
    elif hour < 20:
        return "evening", "wind down, reflective, warm"
    elif hour < 23:
        return "night", "chill, comfortable, easy"
    else:
        return "late night", "deeply introspective, minimal, calm"

def ask_claude(prompt, api_key):
    response = http_post_json(
        'https://api.anthropic.com/v1/messages',
        {
            'model': 'claude-sonnet-4-20250514',
            'max_tokens': 2000,
            'messages': [
                {'role': 'user', 'content': prompt}
            ]
        },
        {
            'x-api-key': api_key,
            'anthropic-version': '2023-06-01'
        }
    )
    return response['content'][0]['text']

def search_spotify_track(track_name, artist, access_token):
    query = urllib.parse.quote(f"{track_name} {artist}")
    result = http_get(
        f'https://api.spotify.com/v1/search?q={query}&type=track&limit=1',
        {'Authorization': f'Bearer {access_token}'}
    )
    tracks = result.get('tracks', {}).get('items', [])
    if tracks:
        return tracks[0]['uri']
    return None

def create_spotify_playlist(user_id, playlist_name, track_uris, access_token):
    playlist = http_post_json(
        f'https://api.spotify.com/v1/users/{user_id}/playlists',
        {
            'name': playlist_name,
            'description': 'Generated by SoulQueue — your personal AI music companion',
            'public': False
        },
        {'Authorization': f'Bearer {access_token}'}
    )
    playlist_id = playlist['id']
    http_post_json(
        f'https://api.spotify.com/v1/playlists/{playlist_id}/tracks',
        {'uris': track_uris},
        {'Authorization': f'Bearer {access_token}'}
    )
    return playlist_id, playlist['external_urls']['spotify']

def build_mood_prompt(mood_input, mood_type, detected_mood, display_name,
                      time_of_day, day_of_week, top_5_artists,
                      top_5_tracks, top_languages, song_profiles):

    base = (
        "You are SoulQueue — a deeply intelligent multilingual music curator.\n"
        "You understand music on emotional, cultural and scientific levels.\n"
        "You never pick generic or boring songs. Every choice must have soul.\n"
        "You understand ALL languages and cultures in music.\n\n"
        "USER PROFILE:\n"
        "Name: " + display_name + "\n"
        "Time: " + time_of_day + " on " + day_of_week + "\n"
        "Languages they listen to: " + ', '.join([l[0] for l in top_languages]) + "\n"
        "Top artists: " + ', '.join([a[0] for a in top_5_artists]) + "\n"
        "Most played songs: " + ', '.join([t[0] for t in top_5_tracks]) + "\n\n"
    )

    if mood_type == 'custom':
        mood_section = (
            "MOOD INPUT FROM USER: " + mood_input + "\n\n"
            "The user typed exactly how they feel in their own words.\n"
            "This could be simple or deeply complex.\n"
            "Your job is to deeply understand it and extract:\n"
            "1. The core emotion and all its layers\n"
            "2. The energy level needed (very low/low/medium/high/very high)\n"
            "3. The perfect audio profile (valence, energy, acousticness)\n"
            "4. Cultural and language context\n"
            "5. What this person needs from music RIGHT NOW\n"
            "6. The energy arc that would serve this feeling\n\n"
            "Never be generic. This person trusted you with exactly how they feel.\n"
            "Honour that with deeply personal, soulful music choices.\n\n"
        )
    elif mood_type == 'suggestion':
        mood_section = (
            "SELECTED MOOD: " + mood_input + "\n\n"
            "The user selected this mood from suggestions.\n"
            "Understand the full depth of this mood:\n"
            "- Its emotional layers\n"
            "- The energy it needs\n"
            "- The audio profile that serves it\n"
            "- Cultural context relevant to this user\n\n"
            "Go beyond the obvious. Dig into the soul of this mood.\n\n"
        )
    else:
        mood_section = (
            "AUTO DETECTED MOOD: " + detected_mood + "\n\n"
            "This mood was detected from the user's listening history.\n"
            "Their music choices reveal how they feel right now.\n"
            "Trust the data and serve this mood deeply.\n\n"
        )

    song_section = (
        "THEIR RECENT SONG PROFILES WITH FULL AUDIO DNA:\n"
        + json.dumps(song_profiles[:15], indent=2) + "\n\n"
    )

    rules = (
        "YOUR TASK:\n"
        "1. Deeply analyse each song's emotional DNA\n"
        "2. Create exactly 10 songs for this exact mood and moment\n"
        "3. Follow a natural energy arc — the playlist must be a journey\n"
        "4. STRICT VARIETY RULES:\n"
        "   - Maximum 2 songs per artist\n"
        "   - Mix languages naturally from their listening history\n"
        "   - 30% well known, 40% less known, 30% hidden gems\n"
        "   - Mix eras: classics + recent + new discoveries\n"
        "   - No two consecutive songs with same energy level\n"
        "   - At least 3 songs they likely haven't heard before\n"
        "5. Never pick bland or generic choices\n"
        "6. Every song must EARN its place in this playlist\n"
        "7. The playlist must feel like a best friend who truly knows them made it\n"
        "8. Consider their multilingual taste — mix languages naturally\n"
        "9. Name the playlist something deeply evocative and personal\n\n"
        "Return ONLY this exact JSON, nothing else:\n"
        '{\n'
        '    "playlist_name": "Deeply evocative name for this exact mood and moment",\n'
        '    "personal_note": "Warm message speaking directly to their soul (3-4 sentences, deeply personal)",\n'
        '    "detected_mood": "The mood you understood from their input",\n'
        '    "energy_arc": "The emotional journey of this playlist in one sentence",\n'
        '    "languages_included": ["language1", "language2"],\n'
        '    "tracks": [\n'
        '        {"track": "Song Name", "artist": "Artist Name", "language": "Language", "why": "Why this song belongs here"},\n'
        '        {"track": "Song Name", "artist": "Artist Name", "language": "Language", "why": "Why this song belongs here"},\n'
        '        {"track": "Song Name", "artist": "Artist Name", "language": "Language", "why": "Why this song belongs here"},\n'
        '        {"track": "Song Name", "artist": "Artist Name", "language": "Language", "why": "Why this song belongs here"},\n'
        '        {"track": "Song Name", "artist": "Artist Name", "language": "Language", "why": "Why this song belongs here"},\n'
        '        {"track": "Song Name", "artist": "Artist Name", "language": "Language", "why": "Why this song belongs here"},\n'
        '        {"track": "Song Name", "artist": "Artist Name", "language": "Language", "why": "Why this song belongs here"},\n'
        '        {"track": "Song Name", "artist": "Artist Name", "language": "Language", "why": "Why this song belongs here"},\n'
        '        {"track": "Song Name", "artist": "Artist Name", "language": "Language", "why": "Why this song belongs here"},\n'
        '        {"track": "Song Name", "artist": "Artist Name", "language": "Language", "why": "Why this song belongs here"}\n'
        '    ]\n'
        '}'
    )

    return base + mood_section + song_section + rules

def lambda_handler(event, context):
    try:
        claude_api_key = get_secret('/soulqueue/claude_api_key')
        users_table = dynamodb.Table('soulqueue-users')
        history_table = dynamodb.Table('soulqueue-listening-history')
        playlists_table = dynamodb.Table('soulqueue-playlists')

        users = users_table.scan()['Items']
        time_of_day, mood_context = get_time_context()
        day_of_week = datetime.now().strftime('%A')

        user_mood = event.get('mood', None)
        mood_type = event.get('mood_type', 'auto')
        time_context = event.get('time_context', time_of_day)

        for user in users:
            try:
                user_id = user['user_id']
                display_name = user.get('display_name', 'there')
                access_token = user['access_token']

                history = history_table.query(
                    KeyConditionExpression=Key('user_id').eq(user_id)
                )['Items']

                if not history:
                    continue

                top_artists = {}
                top_tracks = {}
                languages = {}
                mood_totals = {}

                for item in history:
                    artist = item.get('artist_name', '')
                    track = item.get('track_name', '')
                    language = item.get('language', 'English')
                    mood_scores = item.get('mood_scores', {})

                    top_artists[artist] = top_artists.get(artist, 0) + 1
                    top_tracks[track] = top_tracks.get(track, 0) + 1
                    languages[language] = languages.get(language, 0) + 1

                    for mood_key, score in mood_scores.items():
                        score_float = float(score) if isinstance(score, Decimal) else score
                        mood_totals[mood_key] = mood_totals.get(mood_key, 0) + score_float

                top_5_artists = sorted(
                    top_artists.items(), key=lambda x: x[1], reverse=True
                )[:5]
                top_5_tracks = sorted(
                    top_tracks.items(), key=lambda x: x[1], reverse=True
                )[:5]
                top_languages = sorted(
                    languages.items(), key=lambda x: x[1], reverse=True
                )[:3]
                detected_mood = max(
                    mood_totals.items(), key=lambda x: x[1]
                )[0].replace('_', ' ') if mood_totals else 'in my feels'

                song_profiles = []
                for item in history[:30]:
                    song_profiles.append({
                        'track': item.get('track_name', ''),
                        'artist': item.get('artist_name', ''),
                        'language': item.get('language', 'English'),
                        'valence': float(item.get('valence', 0.5)),
                        'energy': float(item.get('energy', 0.5)),
                        'tempo': float(item.get('tempo', 120)),
                        'acousticness': float(item.get('acousticness', 0.5)),
                        'danceability': float(item.get('danceability', 0.5)),
                        'instrumentalness': float(item.get('instrumentalness', 0)),
                        'genres': item.get('genres', []),
                        'play_count': top_tracks.get(item.get('track_name', ''), 1)
                    })

                prompt = build_mood_prompt(
                    mood_input=user_mood or detected_mood,
                    mood_type=mood_type,
                    detected_mood=detected_mood,
                    display_name=display_name,
                    time_of_day=time_of_day,
                    day_of_week=day_of_week,
                    top_5_artists=top_5_artists,
                    top_5_tracks=top_5_tracks,
                    top_languages=top_languages,
                    song_profiles=song_profiles
                )

                claude_response = ask_claude(prompt, claude_api_key)
                playlist_data = json.loads(claude_response)

                track_uris = []
                track_details = []
                for track in playlist_data['tracks']:
                    uri = search_spotify_track(
                        track['track'],
                        track['artist'],
                        access_token
                    )
                    if uri:
                        track_uris.append(uri)
                        track_details.append(track)

                if track_uris:
                    playlist_id, playlist_url = create_spotify_playlist(
                        user_id,
                        playlist_data['playlist_name'],
                        track_uris,
                        access_token
                    )

                    playlists_table.put_item(
                        Item={
                            'user_id': user_id,
                            'created_at': datetime.now().isoformat(),
                            'playlist_id': playlist_id,
                            'playlist_name': playlist_data['playlist_name'],
                            'personal_note': playlist_data['personal_note'],
                            'detected_mood': playlist_data.get('detected_mood', ''),
                            'energy_arc': playlist_data.get('energy_arc', ''),
                            'languages_included': playlist_data.get('languages_included', []),
                            'playlist_url': playlist_url,
                            'time_of_day': time_of_day,
                            'track_count': len(track_uris),
                            'tracks': track_details,
                            'mood_type': mood_type
                        }
                    )

                    print(f"Created playlist for {display_name}: {playlist_data['playlist_name']}")

            except Exception as user_error:
                print(f"Error for user {user.get('user_id')}: {str(user_error)}")
                continue

        return {
            'statusCode': 200,
            'body': json.dumps({'message': 'Playlists generated successfully'})
        }

    except Exception as e:
        print(f"Error: {str(e)}")
        return {
            'statusCode': 500,
            'body': json.dumps({'error': str(e)})
        }