import json
import boto3
import urllib.request
import urllib.parse
from datetime import datetime, timedelta
from boto3.dynamodb.conditions import Key

dynamodb = boto3.resource('dynamodb', region_name='ap-south-1')
ssm = boto3.client('ssm', region_name='ap-south-1')

def get_secret(name):
    return ssm.get_parameter(
        Name=name,
        WithDecryption=True
    )['Parameter']['Value']

def http_post_json(url, data, headers={}):
    body = json.dumps(data).encode('utf-8')
    headers['Content-Type'] = 'application/json'
    req = urllib.request.Request(url, data=body, headers=headers, method='POST')
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read().decode('utf-8'))

def http_get(url, headers):
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read().decode('utf-8'))

def get_time_context():
    hour = datetime.now().hour
    day = datetime.now().strftime('%A')
    if hour < 7:
        return "late night", "calm, introspective, late night vibes"
    elif hour < 9:
        return "early morning", "gentle wake up, slowly energizing"
    elif hour < 12:
        return "morning", "upbeat, motivated, positive energy"
    elif hour < 14:
        return "lunch", "relaxed, feel good, midday vibes"
    elif hour < 17:
        return "afternoon", "focused, steady energy, productive"
    elif hour < 20:
        return "evening", "wind down, commute home, reflective"
    elif hour < 23:
        return "night", "chill, relaxed, comfortable"
    else:
        return "late night", "calm, introspective, late night vibes"

def ask_claude(prompt, api_key):
    response = http_post_json(
        'https://api.anthropic.com/v1/messages',
        {
            'model': 'claude-sonnet-4-20250514',
            'max_tokens': 1000,
            'messages': [
                {'role': 'user', 'content': prompt}
            ]
        },
        {
            'x-api-key': api_key,
            'anthropic-version': '2023-06-01'
        }
    )
    return response['content'][0]['text']

def search_spotify_track(track_name, artist, access_token):
    query = urllib.parse.quote(f"{track_name} {artist}")
    result = http_get(
        f'https://api.spotify.com/v1/search?q={query}&type=track&limit=1',
        {'Authorization': f'Bearer {access_token}'}
    )
    tracks = result.get('tracks', {}).get('items', [])
    if tracks:
        return tracks[0]['uri']
    return None

def create_spotify_playlist(user_id, playlist_name, track_uris, access_token):
    playlist = http_post_json(
        f'https://api.spotify.com/v1/users/{user_id}/playlists',
        {
            'name': playlist_name,
            'description': 'Generated by SoulQueue - your personal AI music companion',
            'public': False
        },
        {'Authorization': f'Bearer {access_token}'}
    )
    playlist_id = playlist['id']
    http_post_json(
        f'https://api.spotify.com/v1/playlists/{playlist_id}/tracks',
        {'uris': track_uris},
        {'Authorization': f'Bearer {access_token}'}
    )
    return playlist_id, playlist['external_urls']['spotify']

def lambda_handler(event, context):
    try:
        claude_api_key = get_secret('/soulqueue/claude_api_key')
        users_table = dynamodb.Table('soulqueue-users')
        history_table = dynamodb.Table('soulqueue-listening-history')
        playlists_table = dynamodb.Table('soulqueue-playlists')

        users = users_table.scan()['Items']
        time_of_day, mood_context = get_time_context()
        day_of_week = datetime.now().strftime('%A')

        user_mood = event.get('mood', None)
        mood_instruction = ""
        if user_mood:
            mood_instruction = "IMPORTANT: The user is currently feeling '" + user_mood + "'. Prioritise this over historical analysis."

        for user in users:
            try:
                user_id = user['user_id']
                display_name = user.get('display_name', 'there')
                access_token = user['access_token']

                history = history_table.query(
                    KeyConditionExpression=Key('user_id').eq(user_id)
                )['Items']

                if not history:
                    continue

                top_artists = {}
                top_tracks = {}
                for item in history:
                    artist = item.get('artist_name', '')
                    track = item.get('track_name', '')
                    top_artists[artist] = top_artists.get(artist, 0) + 1
                    top_tracks[track] = top_tracks.get(track, 0) + 1

                top_5_artists = sorted(top_artists.items(), key=lambda x: x[1], reverse=True)[:5]
                top_5_tracks = sorted(top_tracks.items(), key=lambda x: x[1], reverse=True)[:5]

                prompt = (
                    "You are SoulQueue, a deeply personal AI music companion.\n\n"
                    "User: " + display_name + "\n"
                    "Time: " + time_of_day + " on " + day_of_week + "\n"
                    "Mood context needed: " + mood_context + "\n"
                    + mood_instruction + "\n\n"
                    "Their top artists this week: " + ', '.join([a[0] for a in top_5_artists]) + "\n"
                    "Their most played songs: " + ', '.join([t[0] for t in top_5_tracks]) + "\n\n"
                    "Create a deeply personal playlist of exactly 10 songs for this exact moment.\n"
                    "Mix their favourite artists with similar artists they might not know yet.\n"
                    "Make it feel like a best friend who really knows their taste made it.\n\n"
                    "Respond in this exact JSON format only, no other text:\n"
                    '{\n'
                    '    "playlist_name": "A creative personal playlist name for this moment",\n'
                    '    "personal_note": "A warm personal message about why you made this playlist (2-3 sentences, speak directly to them)",\n'
                    '    "detected_mood": "What mood you detected from their history",\n'
                    '    "tracks": [\n'
                    '        {"track": "Song Name", "artist": "Artist Name"},\n'
                    '        {"track": "Song Name", "artist": "Artist Name"},\n'
                    '        {"track": "Song Name", "artist": "Artist Name"},\n'
                    '        {"track": "Song Name", "artist": "Artist Name"},\n'
                    '        {"track": "Song Name", "artist": "Artist Name"},\n'
                    '        {"track": "Song Name", "artist": "Artist Name"},\n'
                    '        {"track": "Song Name", "artist": "Artist Name"},\n'
                    '        {"track": "Song Name", "artist": "Artist Name"},\n'
                    '        {"track": "Song Name", "artist": "Artist Name"},\n'
                    '        {"track": "Song Name", "artist": "Artist Name"}\n'
                    '    ]\n'
                    '}'
                )

                claude_response = ask_claude(prompt, claude_api_key)
                playlist_data = json.loads(claude_response)

                track_uris = []
                for track in playlist_data['tracks']:
                    uri = search_spotify_track(
                        track['track'],
                        track['artist'],
                        access_token
                    )
                    if uri:
                        track_uris.append(uri)

                if track_uris:
                    playlist_id, playlist_url = create_spotify_playlist(
                        user_id,
                        playlist_data['playlist_name'],
                        track_uris,
                        access_token
                    )

                    playlists_table.put_item(
                        Item={
                            'user_id': user_id,
                            'created_at': datetime.now().isoformat(),
                            'playlist_id': playlist_id,
                            'playlist_name': playlist_data['playlist_name'],
                            'personal_note': playlist_data['personal_note'],
                            'detected_mood': playlist_data.get('detected_mood', ''),
                            'playlist_url': playlist_url,
                            'time_of_day': time_of_day,
                            'track_count': len(track_uris)
                        }
                    )

                    print(f"Created playlist for {display_name}: {playlist_data['playlist_name']}")

            except Exception as user_error:
                print(f"Error for user {user.get('user_id')}: {str(user_error)}")
                continue

        return {
            'statusCode': 200,
            'body': json.dumps({'message': 'Playlists generated successfully'})
        }

    except Exception as e:
        print(f"Error: {str(e)}")
        return {
            'statusCode': 500,
            'body': json.dumps({'error': str(e)})
        }